set dotenv-load

create day:
    cp -i Templates/Solution.swift Sources/Day{{day}}.swift
    sed -i '' "s|Day00|Day{{day}}|" Sources/Day{{day}}.swift
    cp -i Templates/Test.swift Tests/Day{{day}}.swift
    sed -i '' "s|Day00|Day{{day}}|" Tests/Day{{day}}.swift
    sed -i '' "s|// NEXT DAY|Day{{day}}(),\n  // NEXT DAY|" Sources/AdventOfCode.swift
    curl https://adventofcode.com/2025/day/{{trim_start_match(day, "0")}}/input --cookie session=$SESSION > Sources/Data/Day{{day}}.txt
