# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
- repo: https://github.com/slessans/pre-commit-swift-format
  rev: "fd627de92bdf84a75c924ed95691336d14e94cf1"
  hooks:
    - id: swift-format
      args: ["--configuration", ".swift-format"]
